In [61]:
from os.path import isfile, isdir
from tqdm import tqdm 
import tarfile
import pickle
import numpy as np
import matplotlib.pyplot as plt
from scipy.spatial import distance
from PIL import Image

In [62]:
cifar10_dataset_folder_path = '/home/pranav/My Data/M.Tech/ML/Lab Assignments/Assignment-1/cifar-10-python/cifar-10-batches-py'


In [63]:
def load_label_names():
    return ['airplane', 'automobile', 'bird', 'cat', 'deer', 'dog', 'frog', 'horse', 'ship', 'truck']

# Loading Training Data Set

In [64]:
def load_cfar10_batch(cifar10_dataset_folder_path, batch_id):
    with open(cifar10_dataset_folder_path + '/data_batch_' + str(batch_id), mode='rb') as file:
        # note the encoding type is 'latin1'
        batch = pickle.load(file, encoding='latin1')
        
    features = batch['data'].reshape((len(batch['data']), 3, 32, 32)).transpose(0, 2, 3, 1)
    labels = batch['labels']
        
    return features, labels

# Creating 10 lists to classify training data set

In [65]:
list0 = []
list1 = []
list2 = []
list3 = []
list4 = []
list5 = []
list6 = []
list7 = []
list8 = []
list9 = []

# Classifying Training Data using their respective labels

In [66]:
def trainging_classifier(cifar10_dataset_folder_path):
    global list0
    global list1
    global list2
    global list3
    global list4
    global list5
    global list6
    global list7
    global list8
    global list9

        
    for batch_id in range(1,6):
        print(batch_id)#Iterating over all batches
        features, labels = load_cfar10_batch(cifar10_dataset_folder_path, batch_id)
        for i in range(len(features)): #Classifying all samples to respective class list
            if labels[i] == 0:
                list0.append(features[i])
            elif labels[i] == 1:
                list1.append(features[i])
            elif labels[i] == 2:
                list2.append(features[i])
            elif labels[i] == 3:
                list3.append(features[i])
            elif labels[i] == 4:
                list4.append(features[i])
            elif labels[i] == 5:
                list5.append(features[i])
            elif labels[i] == 6:
                list6.append(features[i])
            elif labels[i] == 7:
                list7.append(features[i])
            elif labels[i] == 8:
                list8.append(features[i])
            elif labels[i] == 9:
                list9.append(features[i])
    list0 = np.array([np.array(im1) for im1 in list0]) #Converting All image lists to numpy arrarys
    list1 = np.array([np.array(im2) for im2 in list1])
    list2 = np.array([np.array(im3) for im3 in list2])
    list3 = np.array([np.array(im4) for im4 in list3])
    list4 = np.array([np.array(im5) for im5 in list4])
    list5 = np.array([np.array(im6) for im6 in list5])
    list6 = np.array([np.array(im7) for im7 in list6])
    list7 = np.array([np.array(im8) for im8 in list7])
    list8 = np.array([np.array(im9) for im9 in list8])
    list9 = np.array([np.array(im0) for im0 in list9])

        
    #print(list0.shape[0])
    
    

trainging_classifier(cifar10_dataset_folder_path)    

1
2
3
4
5


# Computing Average Images and saving them 

In [67]:
                                #Find arrays of all lists
avg0 = np.average(list0,axis=0) 
avg1 = np.average(list1,axis=0)
avg2 = np.average(list2,axis=0)
avg3 = np.average(list3,axis=0)
avg4 = np.average(list4,axis=0)
avg5 = np.average(list5,axis=0)
avg6 = np.average(list6,axis=0)
avg7 = np.average(list7,axis=0)
avg8 = np.average(list8,axis=0)
avg9 = np.average(list9,axis=0)


                                #Converting average array back to images
#print(avg0.shape)
result0 = Image.fromarray(avg0.astype('uint8'))
result1 = Image.fromarray(avg1.astype('uint8'))
result2 = Image.fromarray(avg2.astype('uint8'))
result3 = Image.fromarray(avg3.astype('uint8'))
result4 = Image.fromarray(avg4.astype('uint8'))
result5 = Image.fromarray(avg5.astype('uint8'))
result6 = Image.fromarray(avg6.astype('uint8'))
result7 = Image.fromarray(avg7.astype('uint8'))
result8 = Image.fromarray(avg8.astype('uint8'))
result9 = Image.fromarray(avg9.astype('uint8'))

#print(result2.shape)

#plt.imshow(result)

                             #Commented it as all images have aready been saved
"""      
    # saving the final output  
    # as a PNG file 
result0.save('result0.png')
result1.save('result1.png')
result2.save('result2.png')
result3.save('result3.png')
result4.save('result4.png')
result5.save('result5.png')
result6.save('result6.png')
result7.save('result7.png')
result8.save('result8.png')
result9.save('result9.png')
"""

"      \n    # saving the final output  \n    # as a PNG file \nresult0.save('result0.png')\nresult1.save('result1.png')\nresult2.save('result2.png')\nresult3.save('result3.png')\nresult4.save('result4.png')\nresult5.save('result5.png')\nresult6.save('result6.png')\nresult7.save('result7.png')\nresult8.save('result8.png')\nresult9.save('result9.png')\n"

# Loading Test Batch 

In [68]:
def load_test_batch(cifar10_dataset_folder_path):
    with open(cifar10_dataset_folder_path + '/test_batch' , mode='rb') as file:
        # note the encoding type is 'latin1'
        batch = pickle.load(file, encoding='latin1')
        
    test_samples = batch['data'].reshape((len(batch['data']), 3, 32, 32)).transpose(0, 2, 3, 1)
    test_labels = batch['labels']
        
    return test_samples, test_labels

test_samples, test_labels = load_test_batch(cifar10_dataset_folder_path)    

# Creating Average List (List of lists)

In [69]:
avg_list = list()
avg_list.append(result0)
avg_list.append(result1)
avg_list.append(result2)
avg_list.append(result3)
avg_list.append(result4)
avg_list.append(result5)
avg_list.append(result6)
avg_list.append(result7)
avg_list.append(result8)
avg_list.append(result9)

# Creating a distance matrix
Computing the Eucledian distance b/w 2 images and returning the distance list

In [70]:
def avg_matrix():
    row = list()
    distance_matrix = list()
    #plt.imshow(avg_list[0])
    #print(len(test_samples))
    for i in range(len(test_samples)):
        col = [0]*len(avg_list)
        for j in range(len(avg_list)):
            col[j] = np.linalg.norm(test_samples[i]-avg_list[j])   #Eucledian distance b/w 2 images
        distance_matrix.append(col)
         
    #rint(distance_matrix.sha)
    return distance_matrix
            

# Finding the least distance among all class labels for each test sample

In [72]:
def FindLeastDistance():
    distance_matrix = avg_matrix()
    prediction = list()
    
    for i in range(len(distance_matrix)): #Iterating over the rows
        min1 = float('inf')
        for j in range(len(distance_matrix[0])): #Iterating over the cols
            if (distance_matrix[i][j] < min1 ):
                min1 = distance_matrix[i][j]
        prediction.append(distance_matrix[i].index(min1))
    return prediction

# Computing Accuracy and Error of Test Data

In [73]:
prediction = FindLeastDistance()
score =0
for i in range(len(test_labels)):
    if(test_labels[i]==prediction[i]):
        score +=1                         #Computes the score of the classifer
accuracy = score/len(test_labels)
error = 1 - accuracy
print("Test data Error % = ", error*100)


Test data Error % =  88.72


# Creating a Confusion Matrix

In [84]:
from sklearn.metrics import confusion_matrix

In [87]:
confusion_array = confusion_matrix(test_labels, prediction)
print(confusion_array)

[[251 138  48  23  53  32 196  52  98 109]
 [275  38   5  19  44  62 232  39 111 175]
 [226  63  20   8  46  21 373  33  81 129]
 [240  56   5   8  25  54 298  29  92 193]
 [156  48   6   9  16  15 424  17 122 187]
 [231  45   5  13  13  71 311  22 124 165]
 [253  31   2   6  17  17 381  18  88 187]
 [162  60   7  10  24  25 288  16 185 223]
 [123  92  11  27  83  36 230  69 147 182]
 [237  51   9  20  46  61 213  72 111 180]]


# Exporting Confusion Matrix to an Excel Sheet

In [86]:
import xlsxwriter
workbook = xlsxwriter.Workbook('Confusion_Matrix.xlsx')
worksheet = workbook.add_worksheet()
row = 0
temp = np.transpose(confusion_array) 
for col, data in enumerate(temp):
    worksheet.write_column(row, col, data)

workbook.close()

In [76]:
#Unused Code : Ignore


"""
def display_stats(cifar10_dataset_folder_path, batch_id, sample_id):
    features, labels = load_cfar10_batch(cifar10_dataset_folder_path, batch_id)
    
    if not (0 <= sample_id < len(features)):
        print('{} samples in batch {}.  {} is out of range.'.format(len(features), batch_id, sample_id))
        return None

    print('\nStats of batch #{}:'.format(batch_id))
    print('# of Samples: {}\n'.format(len(features)))
    
    label_names = load_label_names()
    label_counts = dict(zip(*np.unique(labels, return_counts=True)))
    for key, value in label_counts.items():
        print('Label Counts of [{}]({}) : {}'.format(key, label_names[key].upper(), value))
    
    sample_image = features[sample_id]
    sample_label = labels[sample_id]
    
    
    #ims = []
    #ims.append(sample_image)
    
    
    print('\nExample of Image {}:'.format(sample_id))
    print('Image - Min Value: {} Max Value: {}'.format(sample_image.min(), sample_image.max()))
    print('Image - Shape: {}'.format(sample_image.shape))
    print('Label - Label Id: {} Name: {}'.format(sample_label, label_names[sample_label]))
    
    plt.imshow(sample_image)
"""   





"""
def avg_matrix():
    #global test_samples
    #global avg_list
    distance_matrix = [[0] *10]* len(test_samples)
    #plt.imshow(avg_list[0])
    #print(len(test_samples))
    for i in range(len(test_samples)):
        #j=0
        for j in range(len(avg_list)):
            #print(i,j)
            distance_matrix[i][j] = np.linalg.norm(test_samples[i]-avg_list[j])
        
            
    #rint(distance_matrix.sha)
    return distance_matrix
"""            
        
#distance_matrix2 = avg_matrix()
#print(avg_matrix())

'\ndef avg_matrix():\n    #global test_samples\n    #global avg_list\n    distance_matrix = [[0] *10]* len(test_samples)\n    #plt.imshow(avg_list[0])\n    #print(len(test_samples))\n    for i in range(len(test_samples)):\n        #j=0\n        for j in range(len(avg_list)):\n            #print(i,j)\n            distance_matrix[i][j] = np.linalg.norm(test_samples[i]-avg_list[j])\n        \n            \n    #rint(distance_matrix.sha)\n    return distance_matrix\n'